const EN_US = {
    "EN_US": "English (US)",
    "ZH_CN": "Chinese (Simplified)",
    "Header.Bar.Title": "Living Together | Emulator",
    "Header.Bar.Title.Info": "Group Behavior Research Emulator",
    "Header.Bar.File.Name.Info": "{file} ({status})",
    "Header.Bar.New.File.Name": "NewFile.ltss",
    "Header.Bar.File.Save.Status.Saved": "Saved",
    "Header.Bar.File.Save.Status.Unsaved": "UnSaved",
    "Header.Bar.Fps": "FPS: {renderFps} | {physicsFps}",
    "Header.Bar.Fps.Info": "The rendering frame rate ({renderFps} fps) is on the left, and the simulation frame rate ({physicsFps} fps) is on the right.",
    "Header.Bar.Fps.Render.Info": "Render fps {fps}",
    "Header.Bar.Fps.Simulate.Info": "Simulate fps {fps}",
    "Command.Bar.Save.Info": "Save",
    "Command.Bar.Play.Info": "Start simulation",
    "Command.Bar.Drag.Info": "Drag and drop to move the camera",
    "Command.Bar.Select.Info": "Select object",
    "Command.Bar.Add.Group.Info": "Add group object",
    "Command.Bar.Add.Range.Info": "Add scope object",
    "Command.Bar.Add.Behavior.Info": "Add behavior object",
    "Command.Bar.Add.Tag.Info": "Add label object",
    "Command.Bar.Camera.Info": "Renderer settings",
    "Command.Bar.Setting.Info": "Global Settings",
    "Input.Error.Not.Number": "Please key in numbers",
    "Input.Error.Max": "Enter value must be less than {num}",
    "Input.Error.Min": "Enter value must be greater than {num}",
    "Input.Error.Length": "The length of the input content must be less than {num}",
    "Input.Error.Length.Less": "The length of the input content must be greater than {num}",
    "Input.Error.Select": "Select object ...",
    "Input.Error.Combo": "Select options ...",
    "Object.List.New.Group": "Group object {id}",
    "Object.List.New.Range": "Range object {id}",
    "Object.List.New.Label": "Label {id}",
    "Object.List.New.Clip": "Clip {id}",
    "Object.List.No.Data": "There are no objects in the model, click the button to create it",
    "Object.Picker.List.No.Data": "There is no model in the model for this option",
    "Behavior.Picker.Add.Button": "Click here to assign behavior to this group",
    "Behavior.Picker.Add.Nodata": "There is no behavior that can be specified",
    "Panel.Title.Notfound": "{id}",
    "Panel.Info.Notfound": "This panel with id {id} can not found!",
    "Panel.Title.Render.View": "Live preview",
    "Panel.Info.Render.View": "Live simulation results preview",
    "Panel.Title.Object.List.View": "Object list",
    "Panel.Info.Object.List.View": "Edit view all Object Properties",
    "Panel.Title.Range.Details.View": "Range",
    "Panel.Info.Range.Details.View": "Edit view range attributes",
    "Panel.Title.Label.List.View": "Label list",
    "Panel.Info.Label.List.View": "Edit view label list",
    "Panel.Title.Label.Details.View": "Label",
    "Panel.Info.Label.Details.View": "Edit view label attributes",
    "Panel.Title.Group.Details.View": "Group",
    "Panel.Info.Group.Details.View": "Edit view group attributes",
    "Panel.Title.Behavior.List.View": "Behavior list",
    "Panel.Info.Behavior.List.View": "Edit view behavior list",
    "Panel.Title.Behavior.Details.View": "Behavior",
    "Panel.Info.Behavior.Details.View": "Edit view Behavior attributes",
    "Panel.Title.Behavior.Clip.Player": "Recording",
    "Panel.Info.Behavior.Clip.Player": "Pre render recorded data",
    "Panel.Info.Behavior.Clip.Time.Formate": "{current} / {all} / {fps}fps",
    "Panel.Info.Behavior.Clip.Record.Formate": "Record: {time}",
    "Panel.Info.Behavior.Clip.Uname.Clip": "Waiting for recording...",
    "Popup.Title.Unnamed": "Popup message",
    "Popup.Title.Confirm": "Confirm message",
    "Popup.Action.Yes": "Confirm",
    "Popup.Action.No": "Cancel",
    "Popup.Action.Objects.Confirm.Title": "Confirm Delete",
    "Popup.Action.Objects.Confirm.Delete": "Delete",
    "Popup.Action.Objects.Confirm.Restore.Title": "Confirm Restore",
    "Popup.Action.Objects.Confirm.Restore": "Restore",
    "Popup.Delete.Objects.Confirm": "Are you sure you want to delete this object(s)? The object is deleted and cannot be recalled.",
    "Popup.Delete.Behavior.Confirm": "Are you sure you want to delete this behavior? The behavior is deleted and cannot be recalled.",
    "Popup.Delete.Clip.Confirm": "Are you sure you want to delete this clip? The clip cannot be restored after deletion.",
    "Popup.Restore.Behavior.Confirm": "Are you sure you want to reset all parameters of this behavior? This operation cannot be recalled.",
    "Popup.Setting.Title": "Preferences setting",
    "Popup.Offline.Render.Title": "Offline rendering",
    "Popup.Offline.Render.Process.Title": "Rendering progress",
    "Popup.Offline.Render.Message": "Rendering Parameters",
    "Popup.Offline.Render.Input.Name": "Clip name",
    "Popup.Offline.Render.Input.Time": "Duration (s)",
    "Popup.Offline.Render.Input.Fps": "FPS (f/s)",
    "Popup.Offline.Render.Input.Start": "Start rendering",
    "Popup.Offline.Render.Input.End": "Terminate rendering",
    "Popup.Offline.Render.Input.Finished": "Finished",
    "Popup.Offline.Render.Process": "Number of frames completed: {current} / {all}",
    "Popup.Load.Save.Title": "Load save",
    "Popup.Load.Save.confirm": "Got it",
    "Popup.Load.Save.Overwrite": "Overwrite and continue",
    "Popup.Load.Save.Overwrite.Info": "The current workspace will be overwritten after the archive is loaded, and all unsaved progress will be lost. Are you sure you want to continue?",
    "Popup.Load.Save.Error.Empty": "File information acquisition error. The file has been lost or moved.",
    "Popup.Load.Save.Error.Type": "The file with extension name \"{ext}\" cannot be loaded temporarily",
    "Popup.Load.Save.Error.Parse": "Archive parsing error, detailed reason: \n{why}",
    "Popup.Load.Save.Select.Path.Title": "Please select an archive location",
    "Popup.Load.Save.Select.Path.Button": "Save",
    "Popup.Load.Save.Select.File.Name": "Living Together Simulator Save",
    "Popup.Add.Behavior.Title": "Add behavior",
    "Popup.Add.Behavior.Action.Add": "Add all select behavior",
    "Popup.Add.Behavior.Select.Counter": "Selected {count} behavior",
    "Popup.Add.Behavior.Select.Nodata": "Could not find behavior named \"{name}\"",
    "Popup.Behavior.Info.Title": "Behavior details: {behavior}",
    "Popup.Behavior.Info.Confirm": "OK, I know it",
    "Build.In.Label.Name.All.Group": "All group",
    "Build.In.Label.Name.All.Range": "All range",
    "Build.In.Label.Name.Current.Group": "Current group",
    "Common.Search.Placeholder": "Search in here...",
    "Common.No.Data": "No Data",
    "Common.No.Unknown.Error": "Unknown error",
    "Common.Attr.Title.Basic": "Basic properties",
    "Common.Attr.Title.Spatial": "Spatial property",
    "Common.Attr.Title.Individual.Generation": "Individual generation",
    "Common.Attr.Title.Behaviors": "Behaviors list",
    "Common.Attr.Title.Individual.kill": "Individual kill",
    "Common.Attr.Title.Render.Parameter": "Render parameters",
    "Common.Attr.Key.Display.Name": "Display name",
    "Common.Attr.Key.Position.X": "Position X",
    "Common.Attr.Key.Position.Y": "Position Y",
    "Common.Attr.Key.Position.Z": "Position Z",
    "Common.Attr.Key.Radius.X": "Radius X",
    "Common.Attr.Key.Radius.Y": "Radius Y",
    "Common.Attr.Key.Radius.Z": "Radius Z",
    "Common.Attr.Key.Color": "Color",
    "Common.Attr.Key.Display": "Display",
    "Common.Attr.Key.Update": "Update",
    "Common.Attr.Key.Delete": "Delete",
    "Common.Attr.Key.Label": "Label",
    "Common.Attr.Key.Size": "Size",
    "Common.Attr.Key.Error.Multiple": "Multiple values",
    "Common.Attr.Key.Label.Picker.Nodata": "No tags can be added",
    "Common.Attr.Key.Generation": "Generation",
    "Common.Attr.Key.Generation.Mod": "Generation model",
    "Common.Attr.Key.Generation.Mod.Point": "Point model",
    "Common.Attr.Key.Generation.Mod.Range": "Range model",
    "Common.Attr.Key.Generation.Use.Range": "Generation range",
    "Common.Attr.Key.Generation.Count": "Generation count",
    "Common.Attr.Key.Generation.Point.X": "Generation Point X",
    "Common.Attr.Key.Generation.Point.Y": "Generation Point Y",
    "Common.Attr.Key.Generation.Point.Z": "Generation Point Z",
    "Common.Attr.Key.Generation.Error.Empty.Object": "Please select a range object or label to add to the object",
    "Common.Attr.Key.Generation.Error.Empty.Range.List": "The specified label does not contain any scope objects",
    "Common.Attr.Key.Generation.Error.Invalid.Range": "The specified scope object is invalid",
    "Common.Attr.Key.Generation.Error.Invalid.Label": "The specified label has expired",
    "Common.Attr.Key.Kill.Random": "Random kill",
    "Common.Attr.Key.Kill.Count": "Kill count",
    "Common.Attr.Key.Behavior.Restore": "Restore default parameters",
    "Common.Render.Attr.Key.Display.Shape": "Display Shape",
    "Common.Render.Attr.Key.Display.Shape.Square": "Square",
    "Common.Render.Attr.Key.Display.Shape.Hollow.Square": "Hollow square",
    "Common.Render.Attr.Key.Display.Shape.Hollow.Plus": "Plus",
    "Common.Render.Attr.Key.Display.Shape.Hollow.Reduce": "Reduce",
    "Common.Render.Attr.Key.Display.Shape.Hollow.Cross": "Cross",
    "Common.Render.Attr.Key.Display.Shape.Hollow.Checkerboard": "Checkerboard",
    "Panel.Info.Range.Details.Attr.Error.Not.Range": "Object is not a Range",
    "Panel.Info.Range.Details.Attr.Error.Unspecified": "Unspecified range object",
    "Panel.Info.Group.Details.Attr.Error.Not.Group": "Object is not a Group",
    "Panel.Info.Group.Details.Attr.Error.Unspecified": "Unspecified group object",
    "Panel.Info.Label.Details.Error.Unspecified": "Label object not specified",
    "Panel.Info.Label.List.Error.Nodata": "There are no labels in the model, click the button to create",
    "Panel.Info.Behavior.Details.Error.Not.Behavior": "Please specify a behavior first to view the details",
    "Panel.Info.Behavior.Details.Behavior.Props": "{behavior} parameter",
    "Panel.Info.Behavior.Details.Parameter.Key": "{key}",
    "Panel.Info.Behavior.Details.Parameter.Key.Vec.X": "{key} X",
    "Panel.Info.Behavior.Details.Parameter.Key.Vec.Y": "{key} Y",
    "Panel.Info.Behavior.Details.Parameter.Key.Vec.Z": "{key} Z",
    "Panel.Info.Clip.List.Error.Nodata": "There is no clip, please click the record button to record, or click the plus sign to create",
    "Info.Hint.Save.After.Close": "Any unsaved progress will be lost. Are you sure you want to continue?",
    "Info.Hint.Load.File.Title": "Load save",
    "Info.Hint.Load.File.Intro": "Release to load the dragged save file",
}
export default EN_US;