const EN_US = {
    "EN_US": "English (US)",
    "ZH_CN": "Chinese (Simplified)",
    "Header.Bar.Title": "Living Together | Emulator",
    "Header.Bar.Title.Info": "Group Behavior Research Emulator",
    "Header.Bar.File.Name.Info": "{file} ({status})",
    "Header.Bar.New.File.Name": "New File",
    "Header.Bar.File.Save.Status.Saved": "Saved",
    "Header.Bar.File.Save.Status.Unsaved": "UnSaved",
    "Header.Bar.Fps": "FPS: {renderFps} | {physicsFps}",
    "Header.Bar.Fps.Info": "The rendering frame rate ({renderFps} fps) is on the left, and the simulation frame rate ({physicsFps} fps) is on the right.",
    "Command.Bar.Save.Info": "Save",
    "Command.Bar.Play.Info": "Start simulation",
    "Command.Bar.Drag.Info": "Drag and drop to move the camera",
    "Command.Bar.Select.Info": "Select object",
    "Command.Bar.Add.Group.Info": "Add group object",
    "Command.Bar.Add.Range.Info": "Add scope object",
    "Command.Bar.Add.Behavior.Info": "Add behavior object",
    "Command.Bar.Add.Tag.Info": "Add label object",
    "Command.Bar.Camera.Info": "Renderer settings",
    "Command.Bar.Setting.Info": "Global Settings",
    "Input.Error.Not.Number": "Please key in numbers",
    "Input.Error.Max": "Enter value must be less than {num}",
    "Input.Error.Min": "Enter value must be greater than {num}",
    "Input.Error.Length": "The length of the input content must be less than {num}",
    "Input.Error.Length.Less": "The length of the input content must be greater than {num}",
    "Input.Error.Select": "Select object ...",
    "Object.List.New.Group": "Group object {id}",
    "Object.List.New.Range": "Range object {id}",
    "Object.List.New.Label": "Label {id}",
    "Object.List.No.Data": "There are no objects in the model, click the button to create it",
    "Panel.Title.Notfound": "{id}",
    "Panel.Info.Notfound": "This panel with id {id} can not found!",
    "Panel.Title.Render.View": "Live preview",
    "Panel.Info.Render.View": "Live simulation results preview",
    "Panel.Title.Object.List.View": "Object list",
    "Panel.Info.Object.List.View": "Edit view all Object Properties",
    "Panel.Title.Range.Details.View": "Range",
    "Panel.Info.Range.Details.View": "Edit view range attributes",
    "Panel.Title.Label.List.View": "Label list",
    "Panel.Info.Label.List.View": "Edit view label list",
    "Panel.Title.Label.Details.View": "Label",
    "Panel.Info.Label.Details.View": "Edit view label attributes",
    "Panel.Title.Group.Details.View": "Group",
    "Panel.Info.Group.Details.View": "Edit view group attributes",
    "Common.No.Data": "No Data",
    "Common.No.Unknown.Error": "Unknown error",
    "Common.Attr.Title.Basic": "Basic properties",
    "Common.Attr.Title.Spatial": "Spatial property",
    "Common.Attr.Title.Individual.Generation": "Individual generation",
    "Common.Attr.Key.Display.Name": "Display name",
    "Common.Attr.Key.Position.X": "Position X",
    "Common.Attr.Key.Position.Y": "Position Y",
    "Common.Attr.Key.Position.Z": "Position Z",
    "Common.Attr.Key.Radius.X": "Radius X",
    "Common.Attr.Key.Radius.Y": "Radius Y",
    "Common.Attr.Key.Radius.Z": "Radius Z",
    "Common.Attr.Key.Color": "Color",
    "Common.Attr.Key.Display": "Display",
    "Common.Attr.Key.Update": "Update",
    "Common.Attr.Key.Delete": "Delete",
    "Common.Attr.Key.Label": "Label",
    "Common.Attr.Key.Size": "Size",
    "Common.Attr.Key.Error.Multiple": "Multiple values",
    "Common.Attr.Key.Label.Picker.Nodata": "No tags can be added",
    "Common.Attr.Key.Generation": "Generation",
    "Common.Attr.Key.Generation.Mod": "Generation model",
    "Common.Attr.Key.Generation.Mod.Point": "Point model",
    "Common.Attr.Key.Generation.Mod.Range": "Range model",
    "Common.Attr.Key.Generation.Use.Range": "Generation range",
    "Panel.Info.Range.Details.Attr.Error.Not.Range": "Object is not a Range",
    "Panel.Info.Range.Details.Attr.Error.Unspecified": "Unspecified range object",
    "Panel.Info.Group.Details.Attr.Error.Not.Group": "Object is not a Group",
    "Panel.Info.Group.Details.Attr.Error.Unspecified": "Unspecified group object",
    "Panel.Info.Label.Details.Error.Unspecified": "Label object not specified",
    "Panel.Info.Label.List.Error.Nodata": "There are no labels in the model, click the button to create",
}
export default EN_US;