const EN_US = {
    "EN_US": "English (US)",
    "ZH_CN": "Chinese (Simplified)",
    "Header.Bar.Title": "Living Together | Emulator",
    "Header.Bar.Title.Info": "Group Behavior Research Emulator",
    "Header.Bar.File.Name.Info": "{file} ({status})",
    "Header.Bar.New.File.Name": "New File",
    "Header.Bar.File.Save.Status.Saved": "Saved",
    "Header.Bar.File.Save.Status.Unsaved": "UnSaved",
    "Header.Bar.Fps": "FPS: {renderFps} | {physicsFps}",
    "Header.Bar.Fps.Info": "The rendering frame rate ({renderFps} fps) is on the left, and the simulation frame rate ({physicsFps} fps) is on the right.",
    "Command.Bar.Save.Info": "Save",
    "Command.Bar.Play.Info": "Start simulation",
    "Command.Bar.Drag.Info": "Drag and drop to move the camera",
    "Command.Bar.Select.Info": "Select object",
    "Command.Bar.Add.Group.Info": "Add group object",
    "Command.Bar.Add.Range.Info": "Add scope object",
    "Command.Bar.Add.Behavior.Info": "Add behavior object",
    "Command.Bar.Add.Tag.Info": "Add label object",
    "Command.Bar.Camera.Info": "Renderer settings",
    "Command.Bar.Setting.Info": "Global Settings",
    "Panel.Title.Notfound": "{id}",
    "Panel.Info.Notfound": "This panel with id {id} can not found!",
    "Panel.Title.Render.View": "Live preview",
    "Panel.Info.Render.View": "Live simulation results preview",
    "Panel.Title.Object.List.View": "Object list",
    "Panel.Info.Object.List.View": "Edit View All Object Properties",

}
export default EN_US;