const ZH_CN = {
    "EN_US": "英语 (美国)",
    "ZH_CN": "中文 (简体)",
    "Header.Bar.Title": "群生共进 | 仿真器",
    "Header.Bar.Title.Info": "群体行为研究仿真器",
    "Header.Bar.File.Name.Info": "{file} ({status})",
    "Header.Bar.New.File.Name": "新存档",
    "Header.Bar.File.Save.Status.Saved": "已保存",
    "Header.Bar.File.Save.Status.Unsaved": "未保存",
    "Header.Bar.Fps": "帧率: {renderFps} | {physicsFps}",
    "Header.Bar.Fps.Info": "左侧为渲染帧率 ({renderFps} fps), 右侧为模拟帧率 ({physicsFps} fps)。",
    "Command.Bar.Save.Info": "保存",
    "Command.Bar.Play.Info": "开始仿真",
    "Command.Bar.Drag.Info": "拖拽进行视角移动",
    "Command.Bar.Select.Info": "选择对象",
    "Command.Bar.Add.Group.Info": "添加群对象",
    "Command.Bar.Add.Range.Info": "添加范围对象",
    "Command.Bar.Add.Behavior.Info": "添加行为对象",
    "Command.Bar.Add.Tag.Info": "添加标签对象",
    "Command.Bar.Camera.Info": "渲染器设置",
    "Command.Bar.Setting.Info": "全局设置",
    "Input.Error.Not.Number": "请输入数字",
    "Input.Error.Max": "输入数值须小于 {number}",
    "Input.Error.Min": "输入数值须大于 {number}",
    "Input.Error.Length": "输入内容长度须小于 {number}",
    "Input.Error.Length.Less": "输入内容长度须大于 {number}",
    "Input.Error.Select": "选择对象 ...",
    "Object.List.New.Group": "组对象 {id}",
    "Object.List.New.Range": "范围对象 {id}",
    "Object.List.New.Label": "标签 {id}",
    "Object.List.No.Data": "模型中没有任何对象，点击按钮以创建",
    "Object.Picker.List.No.Data": "模型中没有合适此选项的模型",
    "Panel.Title.Notfound": "{id}",
    "Panel.Info.Notfound": "这个编号为 {id} 的面板无法找到!",
    "Panel.Title.Render.View": "实时预览",
    "Panel.Info.Render.View": "实时仿真结果预览",
    "Panel.Title.Object.List.View": "对象列表",
    "Panel.Info.Object.List.View": "编辑查看全部对象列表",
    "Panel.Title.Range.Details.View": "范围",
    "Panel.Info.Range.Details.View": "编辑查看范围属性",
    "Panel.Title.Label.List.View": "标签列表",
    "Panel.Info.Label.List.View": "编辑查看标签列表",
    "Panel.Title.Label.Details.View": "标签",
    "Panel.Info.Label.Details.View": "编辑查看标签属性",
    "Panel.Title.Group.Details.View": "群",
    "Panel.Info.Group.Details.View": "编辑查看群属性",
    "Popup.Title.Unnamed": "弹窗消息",
    "Popup.Title.Confirm": "确认消息",
    "Popup.Action.Yes": "确定",
    "Popup.Action.No": "取消",
    "Popup.Action.Objects.Confirm.Title": "删除确认",
    "Popup.Action.Objects.Confirm.Delete": "删除",
    "Popup.Delete.Objects.Confirm": "你确定要删除这个(些)对象吗？对象被删除将无法撤回。",
    "Popup.Setting.Title": "首选项设置",
    "Popup.Add.Behavior.Title": "添加行为",
    "Popup.Add.Behavior.Action.Add": "添加全部选中行为",
    "Build.In.Label.Name.All.Group": "全部群",
    "Build.In.Label.Name.All.Range": "全部范围",
    "Behavior.Template.Title": "行为",
    "Behavior.Template.Intro": "这是一个模板行为",
    "Common.Search.Placeholder": "在此处搜索...",
    "Common.No.Data": "暂无数据",
    "Common.No.Unknown.Error": "未知错误",
    "Common.Attr.Title.Basic": "基础属性",
    "Common.Attr.Title.Spatial": "空间属性",
    "Common.Attr.Title.Individual.Generation": "生成个体",
    "Common.Attr.Title.Individual.kill": "消除个体",
    "Common.Attr.Key.Display.Name": "显示名称",
    "Common.Attr.Key.Position.X": "X 坐标",
    "Common.Attr.Key.Position.Y": "Y 坐标",
    "Common.Attr.Key.Position.Z": "Z 坐标",
    "Common.Attr.Key.Radius.X": "X 半径",
    "Common.Attr.Key.Radius.Y": "Y 半径",
    "Common.Attr.Key.Radius.Z": "Z 半径",
    "Common.Attr.Key.Color": "颜色",
    "Common.Attr.Key.Display": "显示",
    "Common.Attr.Key.Update": "更新",
    "Common.Attr.Key.Delete": "删除",
    "Common.Attr.Key.Label": "标签",
    "Common.Attr.Key.Size": "大小",
    "Common.Attr.Key.Error.Multiple": "多重数值",
    "Common.Attr.Key.Label.Picker.Nodata": "没有可以被添加的标签",
    "Common.Attr.Key.Generation": "生成",
    "Common.Attr.Key.Generation.Mod": "生成模式",
    "Common.Attr.Key.Generation.Mod.Point": "点生成",
    "Common.Attr.Key.Generation.Mod.Range": "范围生成",
    "Common.Attr.Key.Generation.Use.Range": "生成范围",
    "Common.Attr.Key.Generation.Count": "生成个数",
    "Common.Attr.Key.Generation.Point.X": "生成位置 X 坐标",
    "Common.Attr.Key.Generation.Point.Y": "生成位置 Y 坐标",
    "Common.Attr.Key.Generation.Point.Z": "生成位置 Z 坐标",
    "Common.Attr.Key.Generation.Error.Empty.Object": "请选择一个范围对象或添加至对象的标签",
    "Common.Attr.Key.Generation.Error.Empty.Range.List": "指定的标签中没有包含任何范围对象",
    "Common.Attr.Key.Generation.Error.Invalid.Range": "指定的范围对象已失效",
    "Common.Attr.Key.Generation.Error.Invalid.Label": "指定的标签已失效",
    "Common.Attr.Key.Kill.Random": "随机消除",
    "Common.Attr.Key.Kill.Count": "消除数量",
    "Panel.Info.Range.Details.Attr.Error.Not.Range": "对象不是一个范围",
    "Panel.Info.Range.Details.Attr.Error.Unspecified": "未指定范围对象",
    "Panel.Info.Group.Details.Attr.Error.Not.Group": "对象不是一个群",
    "Panel.Info.Group.Details.Attr.Error.Unspecified": "未指定群对象",
    "Panel.Info.Label.Details.Error.Unspecified": "未指定标签对象",
    "Panel.Info.Label.List.Error.Nodata": "模型中没有标签，点击按钮以创建",
}
export default ZH_CN;