const ZH_CN = {
    "Language": "语言",
    "EN_US": "英语 (美国)",
    "ZH_CN": "中文 (简体)",
    "Themes": "主题",
    "Themes.Dark": "黑暗",
    "Themes.Light": "亮色",
    "Header.Bar.Title": "群生共进 | 仿真器",
    "Header.Bar.Title.Info": "群体行为研究仿真器",
    "Header.Bar.File.Name.Info": "{file} ({status})",
    "Header.Bar.New.File.Name": "新存档.ltss",
    "Header.Bar.File.Save.Status.Saved": "已保存",
    "Header.Bar.File.Save.Status.Unsaved": "未保存",
    "Header.Bar.Fps": "帧率: {renderFps} | {physicsFps}",
    "Header.Bar.Fps.Info": "左侧为渲染帧率 ({renderFps} fps), 右侧为模拟帧率 ({physicsFps} fps)。",
    "Header.Bar.Fps.Render.Info": "渲染帧率 {fps}",
    "Header.Bar.Fps.Simulate.Info": "模拟帧率 {fps}",
    "Command.Bar.Save.Info": "保存",
    "Command.Bar.Play.Info": "开始仿真",
    "Command.Bar.Drag.Info": "拖拽进行视角移动",
    "Command.Bar.Select.Info": "选择对象",
    "Command.Bar.Add.Group.Info": "添加群对象",
    "Command.Bar.Add.Range.Info": "添加范围对象",
    "Command.Bar.Add.Behavior.Info": "添加行为对象",
    "Command.Bar.Add.Tag.Info": "添加标签对象",
    "Command.Bar.Camera.Info": "渲染器设置",
    "Command.Bar.Setting.Info": "全局设置",
    "Input.Error.Not.Number": "请输入数字",
    "Input.Error.Max": "输入数值须小于 {num}",
    "Input.Error.Min": "输入数值须大于 {num}",
    "Input.Error.Length": "输入内容长度须小于 {num}",
    "Input.Error.Length.Less": "输入内容长度须大于 {num}",
    "Input.Error.Select": "选择对象 ...",
    "Input.Error.Combo": "选择选项 ...",
    "Object.List.New.Group": "群对象 {id}",
    "Object.List.New.Range": "范围对象 {id}",
    "Object.List.New.Label": "标签 {id}",
    "Object.List.New.Clip": "剪辑片段 {id}",
    "Object.List.No.Data": "模型中没有任何对象，点击按钮以创建",
    "Object.Picker.List.No.Data": "模型中没有合适此选项的模型",
    "Behavior.Picker.Add.Button": "点击此处以赋予行为到此群",
    "Behavior.Picker.Add.Nodata": "没有可以被指定的行为",
    "Panel.Title.Notfound": "{id}",
    "Panel.Info.Notfound": "这个编号为 {id} 的面板无法找到!",
    "Panel.Title.Render.View": "实时预览",
    "Panel.Info.Render.View": "实时仿真结果预览",
    "Panel.Title.Object.List.View": "对象列表",
    "Panel.Info.Object.List.View": "编辑查看全部对象列表",
    "Panel.Title.Range.Details.View": "范围",
    "Panel.Info.Range.Details.View": "编辑查看范围属性",
    "Panel.Title.Label.List.View": "标签列表",
    "Panel.Info.Label.List.View": "编辑查看标签列表",
    "Panel.Title.Label.Details.View": "标签",
    "Panel.Info.Label.Details.View": "编辑查看标签属性",
    "Panel.Title.Group.Details.View": "群",
    "Panel.Info.Group.Details.View": "编辑查看群属性",
    "Panel.Title.Behavior.List.View": "行为列表",
    "Panel.Info.Behavior.List.View": "编辑查看行为列表",
    "Panel.Title.Behavior.Details.View": "行为",
    "Panel.Info.Behavior.Details.View": "编辑查看行为属性",
    "Panel.Title.Behavior.Clip.Player": "录制",
    "Panel.Info.Behavior.Clip.Player": "预渲染录制数据",
    "Panel.Title.Behavior.Clip.Details": "剪辑",
    "Panel.Info.Behavior.Clip.Details": "编辑查看剪辑片段属性",
    "Panel.Info.Statistics": "查看统计信息",
    "Panel.Title.Statistics": "统计",
    "Panel.Info.Behavior.Clip.Time.Formate": "{current} / {all} / {fps} fps",
    "Panel.Info.Behavior.Clip.Record.Formate": "录制: {time}",
    "Panel.Info.Behavior.Clip.Uname.Clip": "等待录制...",
    "Popup.Title.Unnamed": "弹窗消息",
    "Popup.Title.Confirm": "确认消息",
    "Popup.Action.Yes": "确定",
    "Popup.Action.No": "取消",
    "Popup.Action.Objects.Confirm.Title": "删除确认",
    "Popup.Action.Objects.Confirm.Delete": "删除",
    "Popup.Action.Objects.Confirm.Restore.Title": "重置确认",
    "Popup.Action.Objects.Confirm.Restore": "重置",
    "Popup.Delete.Objects.Confirm": "你确定要删除这个(些)对象吗？对象被删除将无法撤回。",
    "Popup.Delete.Behavior.Confirm": "你确定要删除这个行为吗？行为被删除将无法撤回。",
    "Popup.Delete.Clip.Confirm": "你确定删除这个剪辑片段，剪辑片段删除后将无法恢复。",
    "Popup.Restore.Behavior.Confirm": "你确定要重置此行为的全部参数吗？此操作无法撤回。",
    "Popup.Setting.Title": "首选项设置",
    "Popup.Offline.Render.Title": "离线渲染",
    "Popup.Offline.Render.Process.Title": "渲染进度",
    "Popup.Offline.Render.Message": "渲染参数",
    "Popup.Offline.Render.Input.Name": "剪辑名称",
    "Popup.Offline.Render.Input.Time": "时长 (s)",
    "Popup.Offline.Render.Input.Fps": "帧率 (f/s)",
    "Popup.Offline.Render.Input.Start": "开始渲染",
    "Popup.Offline.Render.Input.End": "终止渲染",
    "Popup.Offline.Render.Input.Finished": "完成",
    "Popup.Offline.Render.Process": "完成帧数: {current} / {all}",
    "Popup.Load.Save.Title": "加载存档",
    "Popup.Load.Save.confirm": "我知道了",
    "Popup.Load.Save.Overwrite": "覆盖并继续",
    "Popup.Load.Save.Overwrite.Info": "存档加载后将覆盖当前工作区，未保存的进度将全部丢失，确定要继续吗?",
    "Popup.Load.Save.Error.Empty": "文件信息获取错误，文件已丢失或已被移动",
    "Popup.Load.Save.Error.Type": "暂时无法加载拓展名为 \"{ext}\" 的文件",
    "Popup.Load.Save.Error.Parse": "存档解析错误，详细原因: \n{why}",
    "Popup.Load.Save.Select.Path.Title": "请选择存档保存位置",
    "Popup.Load.Save.Select.Path.Button": "保存",
    "Popup.Load.Save.Select.File.Name": "群生共进存档",
    "Popup.Add.Behavior.Title": "添加行为",
    "Popup.Add.Behavior.Action.Add": "添加全部选中行为",
    "Popup.Add.Behavior.Select.Counter": "已选择 {count} 个行为",
    "Popup.Add.Behavior.Select.Nodata": "找不到名为 \"{name}\" 的行为",
    "Popup.Behavior.Info.Title": "行为详情: {behavior}",
    "Popup.Behavior.Info.Confirm": "好的, 我知道了",
    "Build.In.Label.Name.All.Group": "全部群",
    "Build.In.Label.Name.All.Range": "全部范围",
    "Build.In.Label.Name.Current.Group": "当前群",
    "Common.Search.Placeholder": "在此处搜索...",
    "Common.No.Data": "暂无数据",
    "Common.No.Unknown.Error": "未知错误",
    "Common.Attr.Title.Basic": "基础属性",
    "Common.Attr.Title.Spatial": "空间属性",
    "Common.Attr.Title.Individual.Generation": "生成个体",
    "Common.Attr.Title.Behaviors": "行为列表",
    "Common.Attr.Title.Individual.kill": "消除个体",
    "Common.Attr.Title.Render.Parameter": "渲染参数",
    "Common.Attr.Key.Display.Name": "显示名称",
    "Common.Attr.Key.Position.X": "X 坐标",
    "Common.Attr.Key.Position.Y": "Y 坐标",
    "Common.Attr.Key.Position.Z": "Z 坐标",
    "Common.Attr.Key.Radius.X": "X 半径",
    "Common.Attr.Key.Radius.Y": "Y 半径",
    "Common.Attr.Key.Radius.Z": "Z 半径",
    "Common.Attr.Key.Color": "颜色",
    "Common.Attr.Key.Display": "显示",
    "Common.Attr.Key.Update": "更新",
    "Common.Attr.Key.Delete": "删除",
    "Common.Attr.Key.Label": "标签",
    "Common.Attr.Key.Size": "大小",
    "Common.Attr.Key.Error.Multiple": "多重数值",
    "Common.Attr.Key.Label.Picker.Nodata": "没有可以被添加的标签",
    "Common.Attr.Key.Generation": "生成",
    "Common.Attr.Key.Generation.Mod": "生成模式",
    "Common.Attr.Key.Generation.Mod.Point": "点生成",
    "Common.Attr.Key.Generation.Mod.Range": "范围生成",
    "Common.Attr.Key.Generation.Use.Range": "生成范围",
    "Common.Attr.Key.Generation.Count": "生成个数",
    "Common.Attr.Key.Generation.Point.X": "生成位置 X 坐标",
    "Common.Attr.Key.Generation.Point.Y": "生成位置 Y 坐标",
    "Common.Attr.Key.Generation.Point.Z": "生成位置 Z 坐标",
    "Common.Attr.Key.Generation.Error.Empty.Object": "请选择一个范围对象或添加至对象的标签",
    "Common.Attr.Key.Generation.Error.Empty.Range.List": "指定的标签中没有包含任何范围对象",
    "Common.Attr.Key.Generation.Error.Invalid.Range": "指定的范围对象已失效",
    "Common.Attr.Key.Generation.Error.Invalid.Label": "指定的标签已失效",
    "Common.Attr.Key.Kill.Random": "随机消除",
    "Common.Attr.Key.Kill.Count": "消除数量",
    "Common.Attr.Key.Behavior.Restore": "还原默认参数",
    "Common.Render.Attr.Key.Display.Shape": "显示形状",
    "Common.Render.Attr.Key.Display.Shape.Square": "方形",
    "Common.Render.Attr.Key.Display.Shape.Hollow.Square": "空心方形",
    "Common.Render.Attr.Key.Display.Shape.Hollow.Plus": "加号",
    "Common.Render.Attr.Key.Display.Shape.Hollow.Reduce": "减号",
    "Common.Render.Attr.Key.Display.Shape.Hollow.Cross": "叉号",
    "Common.Render.Attr.Key.Display.Shape.Hollow.Checkerboard": "棋盘",
    "Panel.Info.Range.Details.Attr.Error.Not.Range": "对象不是一个范围",
    "Panel.Info.Range.Details.Attr.Error.Unspecified": "未指定范围对象",
    "Panel.Info.Group.Details.Attr.Error.Not.Group": "对象不是一个群",
    "Panel.Info.Group.Details.Attr.Error.Unspecified": "未指定群对象",
    "Panel.Info.Label.Details.Error.Unspecified": "未指定标签对象",
    "Panel.Info.Label.List.Error.Nodata": "模型中没有标签，点击按钮以创建",
    "Panel.Info.Behavior.Details.Error.Not.Behavior": "请先指定一个行为以查看详情",
    "Panel.Info.Behavior.Details.Behavior.Props": "{behavior}参数",
    "Panel.Info.Behavior.Details.Parameter.Key": "{key}",
    "Panel.Info.Behavior.Details.Parameter.Key.Vec.X": "{key} X 坐标",
    "Panel.Info.Behavior.Details.Parameter.Key.Vec.Y": "{key} Y 坐标",
    "Panel.Info.Behavior.Details.Parameter.Key.Vec.Z": "{key} Z 坐标",
    "Panel.Info.Clip.List.Error.Nodata": "没有剪辑片段，请点击录制按钮录制，或者点击加号创建",
    "Panel.Info.Clip.Details.Error.Nodata": "请指定一个剪辑片段以查看属性",
    "Panel.Info.Statistics.Nodata": "模型或剪辑中不存在任何群",
    "Info.Hint.Save.After.Close": "任何未保存的进度都会丢失, 确定要继续吗?",
    "Info.Hint.Load.File.Title": "加载存档",
    "Info.Hint.Load.File.Intro": "释放以加载拽入的存档",
}
export default ZH_CN;