const ZH_CN = {
    "EN_US": "英语 (美国)",
    "ZH_CN": "中文 (简体)",
    "Header.Bar.Title": "群生共进 | 仿真器",
    "Header.Bar.Title.Info": "群体行为研究仿真器",
    "Header.Bar.File.Name.Info": "{file} ({status})",
    "Header.Bar.New.File.Name": "新存档",
    "Header.Bar.File.Save.Status.Saved": "已保存",
    "Header.Bar.File.Save.Status.Unsaved": "未保存",
    "Header.Bar.Fps": "帧率: {renderFps} | {physicsFps}",
    "Header.Bar.Fps.Info": "左侧为渲染帧率 ({renderFps} fps), 右侧为模拟帧率 ({physicsFps} fps)。",
    "Command.Bar.Save.Info": "保存",
    "Command.Bar.Play.Info": "开始仿真",
    "Command.Bar.Drag.Info": "拖拽进行视角移动",
    "Command.Bar.Select.Info": "选择对象",
    "Command.Bar.Add.Group.Info": "添加群对象",
    "Command.Bar.Add.Range.Info": "添加范围对象",
    "Command.Bar.Add.Behavior.Info": "添加行为对象",
    "Command.Bar.Add.Tag.Info": "添加标签对象",
    "Command.Bar.Camera.Info": "渲染器设置",
    "Command.Bar.Setting.Info": "全局设置",
    "Input.Error.Not.Number": "请输入数字",
    "Input.Error.Max": "输入数值须小于 {number}",
    "Input.Error.Min": "输入数值须大于 {number}",
    "Input.Error.Length": "输入内容长度须小于 {number}",
    "Object.List.New.Group": "组对象 {id}",
    "Object.List.New.Range": "范围对象 {id}",
    "Object.List.No.Data": "模型中没有任何对象，点击按钮以创建",
    "Panel.Title.Notfound": "{id}",
    "Panel.Info.Notfound": "这个编号为 {id} 的面板无法找到!",
    "Panel.Title.Render.View": "实时预览",
    "Panel.Info.Render.View": "实时仿真结果预览",
    "Panel.Title.Object.List.View": "对象列表",
    "Panel.Info.Object.List.View": "编辑查看全部对象属性",
    "Panel.Title.Range.Details.View": "范围属性",
    "Panel.Info.Range.Details.View": "编辑查看范围属性",
    "Common.Attr.Key.Display.Name": "显示名称",
    "Common.Attr.Key.Position.X": "X 坐标",
    "Common.Attr.Key.Position.Y": "Y 坐标",
    "Common.Attr.Key.Position.Z": "Z 坐标",
    "Common.Attr.Key.Radius.X": "X 半径",
    "Common.Attr.Key.Radius.Y": "Y 半径",
    "Common.Attr.Key.Radius.Z": "Z 半径",
    "Common.Attr.Key.Color": "颜色",
    "Common.Attr.Key.Display": "显示",
    "Common.Attr.Key.Update": "更新",
    "Common.Attr.Key.Error.Multiple": "多重数值",
    "Panel.Info.Range.Details.Attr.Error.Not.Range": "对象不是一个范围",
    "Panel.Info.Range.Details.Attr.Error.Unspecified": "未指定范围对象",
}
export default ZH_CN;