kind: pipeline
type: docker
name: LivingTogether-Lab

steps:
- name: npm build
  pull: if-not-exists
  image: node
  commands:
  - npm config set registry https://registry.npm.taobao.org
  - npm ci
  - npm run release-lab
  - cp -r build/* /http/demo/living-together-lab/
