kind: pipeline
type: docker
name: LivingTogether-Lab

workspace:
  path: /drone/src

steps:
- name: npm build
  pull: if-not-exists
  image: node
  volumes:
  - name: publish
    path: /tmp/cache
  - name: node_modules
    path: /drone/src/node_modules
  commands:
  - npm config set registry https://registry.npm.taobao.org
  - npm ci
  - npm run release-lab
  - mkdir -p /tmp/cache
  - cp -f -r build/* /tmp/cache

volumes:
- name: publish
  host:
    path: /http/demo/living-together-lab
- name: node_modules
  host:
    path: /tmp/node_modules/living-together