kind: pipeline
type: docker
name: LivingTogether-Lab

workspace:
  path: /drone/src

steps:
- name: npm build
  pull: if-not-exists
  image: node
  volumes:
  - name: publish_lab
    path: /drone/src/build_lab
  - name: publish_web
    path: /drone/src/build_web
  - name: node_modules
    path: /drone/src/node_modules
  commands:
  - npm config set registry https://registry.npm.taobao.org
  - npm ci
# - npm run release-lab
# - rm -rf ./build_lab/*
# - cp ./build/* ./build_lab
  - npm run release-web
  - rm -rf ./build_web/*
  - cp ./build/* ./build_web

volumes:
- name: publish_lab
  host:
    path: /http/living-together-lab
- name: publish_web
  host:
    path: /http/living-together-web
- name: node_modules
  host:
    path: /tmp/node_modules/living-together

trigger:
  branch:
  - master