kind: pipeline
type: docker
name: LivingTogether-Lab

steps:
- name: npm build
  pull: if-not-exists
  image: node
  volumes:
  - name: publish
    path: /tmp/cache
  commands:
  - npm config set registry https://registry.npm.taobao.org
  - npm ci
  - npm run release-lab
  - mkdir /tmp/cache
  - cp -r build/* /tmp/cache

volumes:
- name: publish
  host:
    path: /http/demo/living-together-lab